version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: dentite-postgres
    environment:
      POSTGRES_DB: dentite
      POSTGRES_USER: dentite_user
      POSTGRES_PASSWORD: dentite_password
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dentite_user -d dentite"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: dentite-backend
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://dentite_user:dentite_password@postgres:5432/dentite
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
    command: npm run dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: dentite-frontend
    environment:
      VITE_API_URL: http://localhost:3000
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    command: npm run dev

volumes:
  postgres_data:

